twitter: '@albrzs'
site:
  title: Jose Albizures
  description:
    I'm Jose - I'm a web developer from Guatemala ğŸ‡¬ğŸ‡¹ living at
    Moscow ğŸ‡·ğŸ‡º, studing at Bauman Moscow State Technical
    University.
  baseUrl: /
  keywords:
    - dev
    - developer
    - development
    - webdev
    - css
    - javascript
pages:
  - url: '/blog'
    label: 'blog'
    fullLabel: 'ğŸ§‘â€ğŸ’» Sometimes I write stuff'
    showInHome: true
    asTopLink: false
    external: false
  - url: 'https://github.com/albizures'
    label: 'github'
    showInHome: false
    asTopLink: true
    external: true
  - url: 'https://twitter.com/albzrs'
    label: 'twitter'
    showInHome: false
    asTopLink: true
    external: true
  - url: '/listening'
    label: 'listening'
    fullLabel: 'ğŸ¶ I like to listen to music and make playlists'
    showInHome: false
    asTopLink: false
    external: false
  - url: 'https://instagram.com/albzrs'
    label: 'instagram'
    showInHome: false
    asTopLink: true
    external: true
  - url: '/building'
    label: 'building'
    fullLabel: 'ğŸ›  I like to build things'
    showInHome: true
    asTopLink: false
    external: false
